import { Injectable } from '@angular/core';
    
@Injectable()
export class clientlistService {
    getClientData() {
        return [
            {
                id: '1',
                name:'Mr. Charles Smith',
                countaddress: 2,
                addresstype: 'Residence',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'cssmith@gmail.com',
                phonetype:'Mobile',
                primaryphone: '(605) 583-9234',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: '',
                isloading: true,
                clienttype: 'My Client',
                countmobilenumber: 3,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'02-26-1991',
                ssn:36734734637,
            },
            {
                id: '2',
                name:'Mrs. Beth Smith',
                countaddress: 1,
                addresstype: 'Rented',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                primaryemail: 'beth_smith@gmail.com',
                phonetype:'Residence',
                primaryphone: '(605) 965-1245',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: 'As of June 2, 2024',
                isloading: false,
                clienttype: 'CRM Client',
                countmobilenumber: 1,
                mobilenumber1: '(601) 623 6251',
                dob:'03-12-2001',
                ssn:23642376427,
            },
            {
                id: '3',
                name:'Mrs. John Barnes',
                countaddress: 2,
                addresstype: 'Office',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'john_barens@gmail.com',
                phonetype:'Office',
                primaryphone: '(605) 328-9347',
                loanbalance: '$134,843.82',
                assetsbalance: '$657,836.19',
                accbalanceasof: '',
                isloading: false,
                clienttype: 'My Client',
                countmobilenumber: 2,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                dob:'02-26-1991',
                ssn:36734734637,
            },
            {
                id: '4',
                name:'Mrs. Mary P. Barens',
                countaddress: 1,
                addresstype: 'Living with parents',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                primaryemail: 'mary_p@gmail.com',
                phonetype:'Mobile',
                primaryphone: '(605) 485-2734',
                loanbalance: '$134,843.82',
                assetsbalance: '$657,836.19',
                accbalanceasof: 'As of June 2, 2024',
                isloading: false,
                clienttype: 'My Client',
                countmobilenumber: 3,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'03-12-2001',
                ssn:23642376427,
            },
            {
                id: '5',
                name:'Mr. Charles Smith',
                countaddress: 2,
                addresstype: 'Residence',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'cssmith@gmail.com',
                phonetype:'Residence',
                primaryphone: '(605) 583-9234',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: '',
                isloading: false,
                clienttype: 'CRM Client',
                countmobilenumber: 3,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'02-26-1991',
                ssn:36734734637,
            },
            {
                id: '6',
                name:'Mrs. Beth Smith',
                countaddress: 1,
                addresstype: 'Rented',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                primaryemail: 'beth_smith@gmail.com',
                phonetype:'Office',
                primaryphone: '(605) 965-1245',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: '',
                isloading: false,
                clienttype: 'My Client',
                countmobilenumber: 1,
                mobilenumber1: '(601) 623 6251',
                dob:'03-12-2001',
                ssn:23642376427,
            },
            {
                id: '7',
                name:'Mrs. John Barnes',
                countaddress: 2,
                addresstype: 'Office',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'john_barens@gmail.com',
                phonetype:'Mobile',
                primaryphone: '(605) 328-9347',
                loanbalance: '$134,843.82',
                assetsbalance: '$657,836.19',
                accbalanceasof: 'As of June 2, 2024',
                isloading: false,
                clienttype: 'My Client',
                countmobilenumber: 3,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'02-26-1991',
                ssn:36734734637,
            },
            {
                id: '8',
                name:'Mrs. Mary P. Barens',
                countaddress: 2,
                addresstype: 'Living with parents',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'mary_p@gmail.com',
                phonetype:'Residence',
                primaryphone: '(605) 485-2734',
                loanbalance: '$134,843.82',
                assetsbalance: '$657,836.19',
                accbalanceasof: '',
                isloading: true,
                clienttype: 'CRM Client',
                countmobilenumber: 2,
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'03-12-2001',
                ssn:23642376427,
            },
            {
                id: '9',
                name:'Mr. Charles Smith',
                countaddress: 2,
                addresstype: 'Residence',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'cssmith@gmail.com',
                phonetype:'Office',
                primaryphone: '(605) 583-9234',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: '',
                isloading: false,
                clienttype: 'CRM Client',
                countmobilenumber: 3,
                mobilenumber1: '(601) 623 6251',
                mobilenumber2: '(615) 237 1923',
                mobilenumber3: '(612) 843 7541',
                dob:'02-26-1991',
                ssn:36734734637,
            },
            {
                id: '10',
                name:'Mrs. Beth Smith',
                countaddress: 2,
                addresstype: 'Rented',
                address1: '#805 Hilll Rapid, Port Santos, KY 70785',
                address2: '#301 Street Road, Lake SIde, KY 47236',
                primaryemail: 'beth_smith@gmail.com',
                phonetype:'Mobile',
                primaryphone: '(605) 965-1245',
                loanbalance: '$0.00',
                assetsbalance: '$869,801.42',
                accbalanceasof: 'As of June 2, 2024',
                isloading: false,
                clienttype: 'My Client',
                countmobilenumber: 1,
                mobilenumber3: '(612) 843 7541',
                dob:'03-12-2001',
                ssn:23642376427,
            },
        ];
    }

    getClientsMini() {
        return Promise.resolve(this.getClientData().slice(0, 10));
    }

    getClientsSmall() {
        return Promise.resolve(this.getClientData().slice(0, 10));
    }

    getClients() {
        return Promise.resolve(this.getClientData());
    }

};